---
title: "Data Exporting in R"
format: html
editor: visual
---

## Getting the Data

The data comes from page [link](https://boston-pd-crime-hub-boston.hub.arcgis.com/pages/data). I have previously downloaded the file on crime incidences (offenses):

```{r}
LinkData="https://github.com/DACSS-PreProcessing/DFops_exporting/raw/refs/heads/main/originalData/Boston_Incidents.csv"

boston=read.csv(LinkData)
```

Check data types:

```{r}
str(boston)
```

```{r}
# then
# boston$Report.Date=strptime(boston$Report.Date, "%m/%d/%Y %I:%M:%S")
boston$Report.Date=as.POSIXct(boston$Report.Date, format =  "%m/%d/%Y %I:%M:%S %p", tz = 'UTC') 
boston$Quarter=as.ordered(boston$Quarter)
# types
str(boston)
```

```{r}
saveRDS(boston,file = "from_r.rds")
write.csv(boston,"from_r.csv")
arrow::write_parquet(boston,sink = "from_r.parquet")
arrow::write_feather(boston,sink = "from_r.feather")

```

```{r}
rds_from_py=readRDS("from_py.rds")
str(rds_from_py)
```

```{r}
feather_from_py=arrow::read_feather(file = "from_py.feather")
str(feather_from_py)
```

```{r}
parquet_from_py=arrow::read_parquet(file = "from_py.parquet")
str(parquet_from_py)
```

```{r}
featherLink='https://github.com/DACSS-PreProcessing/DFops_exporting/raw/refs/heads/main/from_py.feather'


feather_from_py=arrow::read_feather(file = featherLink)
str(feather_from_py)
```

```{r}
featherLink_r='https://github.com/DACSS-PreProcessing/DFops_exporting/raw/refs/heads/main/from_r.feather'


feather_from_r=arrow::read_feather(file = featherLink_r)
str(feather_from_r)
```

```{r}
parquetLink_py='https://github.com/DACSS-PreProcessing/DFops_exporting/raw/refs/heads/main/from_py.parquet'


parquet_from_py=arrow::read_parquet(file = parquetLink_py)
str(parquet_from_py)
```
